# Generated by Django 3.2.5 on 2021-07-16 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainup_core', '0002_auto_20210711_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='entry_date',
            field=models.DateField(default=datetime.date(2021, 7, 16)),
        ),
    ]
